import fs from 'fs';
import path from 'path';

const icon192 = Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAQAAABoP+JjAAAAc0lEQVR42u3BAQ0AAADCoPdPbQ8HFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuA72RAAB2nL2WwAAAABJRU5ErkJggg==',
    'base64'
);
const icon512 = Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAABAklEQVR42u3BAQ0AAADCoPdPbQ8HFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwZpB9AAEW6iIEAAAAAElFTkSuQmCC',
    'base64'
);

fs.writeFileSync(path.join(process.cwd(), 'public', 'pwa-192x192.png'), icon192);
fs.writeFileSync(path.join(process.cwd(), 'public', 'pwa-512x512.png'), icon512);

console.log('Icons created successfully');
